### ISSUE TITLE
Short args can't be used with =

### ISSUE THREAD

**Issue by jaydenseric** [vercel/arg#51]
Short args can't be used with `=`. Is this intentional?

```js
const arg = require('arg')

arg({
  '-a': String
})
```

```sh
node example.js -a=a
```

Results in:

```
                                        throw new TypeError(`Option requires argument (but was followed by another short argument): ${originalArgName}`);
                                        ^

TypeError: Option requires argument (but was followed by another short argument): -a
    at arg (<path>/node_modules/arg/index.js:97:12)
    at Object.<anonymous> (<path>/example.js:5:1)
```

A similar error happens for aliases:

```js
const arg = require('arg')

arg({
  '--a': String,
  '-a': '--a'
})
```

**Comment by Qix-** [comment]
A short arg with an equal sign is not part of the GNU command line arguments guidelines (which `arg` tries to follow as best as possible). Seeing `-a=a` looks really strange to me - you'd either do `-aa` or `-a a`.

Does `--a=a` work in the second example?

**Comment by jaydenseric** [comment]
Good do know about the GNU command line arguments guidelines, but is it ubiquitous? [`yargs`](https://npm.im/yargs) works with short args and `=` just fine. I'm having to document this as a breaking change in `jsdoc-md`, migrating from `yargs`: https://github.com/jaydenseric/jsdoc-md/blob/master/changelog.md#major.

> Does `--a=a` work in the second example?

Yes.

**Comment by Qix-** [comment]
Comes down to scope creep, really. It's a tradeoff between having a consistent and intuitive CLI format, or supporting arguments in any format one can imagine. This library happens to take the former stance.

For what it's worth, I've never seen a CLI program accept `-name=arg` as a short-arg. The only thing I can think of that comes close is `java`/`javac`'s use of short args (e.g. `java -version`) but I've always found that to be against the grain, too.

While it's a breaking change, it'll be a breaking change for the better IMO.

**Comment by jaydenseric** [comment]
> I've never seen a CLI program accept `-name=arg` as a short-arg.

For that to be true, that would mean you've never used a CLI that uses `yargs`.

**Comment by Qix-** [comment]
Sorry, should have said that I've never seen a command line written that way. If I have, I sure don't remember it.

**Comment by Qix-** [comment]
Going to close this as I don't think there's anything actionable. Thank you for the input :)

**Comment by jaeee5** [comment]
Hi i dont know is anyone can help but i am getting this error when attempting to run 
`vercel deploy -prebuilt`

`throw new ArgError(`option requires argument: ${originalArgName}${extended}`, 'ARG_MISSING_REQUIRED_LONGARG');`

**Comment by personession** [comment]
> Hi i dont know is anyone can help but i am getting this error when attempting to run `vercel deploy -prebuilt`
> 
> `throw new ArgError(`option requires argument: ${originalArgName}${extended}`, 'ARG_MISSING_REQUIRED_LONGARG');`

May I ask how you solved this  problem?
