### ISSUE TITLE
Is there other way to input array of strings?

### ISSUE THREAD

**Issue by CursedMun** [vercel/arg#54]
For example, I have this arg `"--tte": [String],` so whenever I call the program I need to write `myScript --tte event` is there a way to write multiple string without repeating --tte multiple times and splinting with commas?

**Comment by Qix-** [comment]
Unfortunately not; which way would you have in mind?

**Comment by CursedMun** [comment]
I managed to work around it using commas to separate it. But I think you could assign the separator would look something like `"--tte": [string,"|"]` or even for multiple separators `"--tte": [string,["|",","]]`

**Comment by Qix-** [comment]
I don't think this would be something we'd want as it doesn't really follow any GNU argument conventions (which is what this library tries to model). I think the following would be the preferable way:

```javascript
arg['--tte'] = arg['--tte'].split(/[|,]/g);
```
