### ISSUE TITLE
Add support for running in the browser

### ISSUE THREAD

**Issue by dhruvkb** [vercel/arg#56]
https://github.com/vercel/arg/blob/99b578ee3e7822c8e42a02907c02f58f5d2745e8/index.js#L13

The library takes the default argument vector from `process.env`. As a result, the library does not work in the browser. Removing the default fixes this.

I understand that this is an unconventional use-case and that `arg` is an opinionated library so this might be outside the scope, but if it isn't I'm more than happy to make a PR from my fork (that I currently use to work around this limitation).

**Comment by yuler** [comment]
You can pass argv like this

```js
arg({}, {argv: '--demo'})
```

![image](https://user-images.githubusercontent.com/6996341/123390114-23c42080-d5cd-11eb-9d47-381966bd8544.png)

It will work

**Comment by Qix-** [comment]
@yuler is correct. Readme tells all, by the way 😉
