### ISSUE TITLE
Typescript build error

### ISSUE THREAD

**Issue by lfernando2091** [vercel/arg#59]
When implement the module in typescript and built it, I get the next error when I trying to run 

`const args = (0, arg_1.default)({
        '--v': Boolean,
        '--a': Boolean,
        '-v': '--v',
        '-a': '--a'
    });`
UnhandledPromiseRejectionWarning: TypeError: (0 , arg_1.default) is not a function

**Comment by Qix-** [comment]
Take it up with Typescript, this doesn't have anything to do with Arg.
