### ISSUE TITLE
Add support for Deno

### ISSUE THREAD

**Issue by vixalien** [vercel/arg#65]
Title speaks for itself (I believe). It would largely just work by using esm

**Comment by leerob** [comment]
@Qix- publish rights need to remain with Vercel employees (sorry 😢). Would still love to have you here as a contributor, but I understand (and you probably don't want the notifications). Will remove you now.

**Comment by Qix-** [comment]
A bit sad seeing as how I literally wrote this package from scratch while I worked there, but I suppose I understand. What I don't really get is how having...

```javascript
document.querySelectorAll('.cf > *').length 
```

... **179** collaborators with write access on npm is considered secure by Vercel's standards, and why the **original author** of the package, a former Vercel employee and established member of the Node.js community, is unable to have access to one or two packages to help maintain them.

A bit sad to see an end of an era. Sorry to @vixalien to derail the issue a bit but it seems my old colleagues at Vercel don't like responding to me in other channels anymore, either.

If this is truly the case, can you please remove me from the other repositories in the Vercel org, too?

**Comment by leerob** [comment]
Thanks for the shout on others with write access – I will review that list as well too and ensure they are all Vercel employees. I do appreciate all of your work here (and your work during your time at Vercel) and you'll remain [the author](https://github.com/vercel/arg/blob/main/package.json#L8) for the package 🙏 

@vixalien I'm going to open an issue for ESM support - thank you!
